version: '3.8'

services:
  kronos-api:
    build:
      context: ../..
      dockerfile: services/kronos_fastapi/Dockerfile
    image: kronos-fastapi:latest
    container_name: kronos-api
    hostname: kronos-api

    # Environment variables
    environment:
      - KRONOS_APP_NAME=Kronos FastAPI Service
      - KRONOS_LOG_LEVEL=${KRONOS_LOG_LEVEL:-INFO}
      - KRONOS_MODEL_PATH=/models
      - KRONOS_DEVICE=${KRONOS_DEVICE:-cpu}
      - KRONOS_MAX_CONTEXT=512
      - KRONOS_DEFAULT_PRED_LEN=120
      - KRONOS_DEFAULT_TEMPERATURE=1.0
      - KRONOS_DEFAULT_TOP_P=0.9
      - KRONOS_ENABLE_METRICS=true

    # Volumes
    volumes:
      - ${KRONOS_MODEL_HOST_PATH:-../../../models}:/models:ro  # Read-only model files
      - logs:/logs  # Persistent logs

    # Networks
    networks:
      - kronos-internal

    # No external port mapping for security (internal access only)
    # To access from host for testing, temporarily uncomment below:
    # ports:
    #   - "8000:8000"

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  kronos-internal:
    driver: bridge
    # Set to true for complete isolation (no internet access)
    # Set to false to allow model downloads from Hugging Face
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
    driver: local
